[dependencies]
actix-web = "2.0"               # Actix web
actix-rt = "1.1"                # Actix runtime
actix-identity = "0.2"          # Identity
serde = "1.0"                   # serialization
serde_json = "1.0"              # serialization for JSON
log = "0.4"                     # logging
env_logger = "0.7"              # logging
derive_more = "0.99"
futures = "0.3"                 # async
lazy_static = "1.4"             # runtime const evaluation
jsonschema = "0.3"              # JSON schema
rand = "0.7.3"                  # random value generator
uuid = { version = "0.8", features = ["v4"] } # UUID

argonautica = "0.2"  # argon2 password hashing
hmac = "0.9.0"       # for api token hashing
sha2 = "0.9.1"       # for api token hashing
hex = "0.4.2"        # for encoding the bytes from hmac to a postgres TEXT field

diesel = { version = "1.4.4", features = ["postgres", "chrono", "r2d2", "serde_json"] } # Database
chrono = { version = "0.4.11", features = ["serde"] } # time
dotenv = "0.15.0"                                     # environment variables
r2d2 = "0.8"                                          # Database pooling
diesel_migrations = "1.4"       # Embedding database migration
