[package]
name = "cargo-expand"
version = "0.4.12"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Wrapper around rustc --pretty=expanded. Shows the result of macro expansion and #[derive] expansion."
repository = "https://github.com/dtolnay/cargo-expand"
documentation = "https://github.com/dtolnay/cargo-expand"
keywords = ["cargo", "subcommand", "expanded"]
categories = ["development-tools::cargo-plugins", "development-tools::debugging"]
edition = "2018"
readme = "README.md"

[dependencies.beta]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[dependencies]
atty = "0.2"
prettyprint = "0.6"
proc-macro2 = "0.4"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"
syn-select = "0.1.4"
tempfile = "3.0"
termcolor = "1.0"
toml = "0.5"
quote = { version = "0.6", default-features = false }
toolchain_find = "0.1"

#hello
[dependencies.alpha]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[dependencies.syn]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[dev-dependencies.cde]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[dev-dependencies.bcd.xyz]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[build-dependencies.cde]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[dev-dependencies.abc]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[build-dependencies]
hello = "0.0.0"
aaa = "0.0.0"

[build-dependencies.bcd]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[build-dependencies.abc]
version = "0.15"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[badges]
travis-ci = { repository = "dtolnay/cargo-expand" }
