# oh yea
[dependencies]
c = "0"

# above D
d = "0"
a = "0"
b = "0"

[dependencies.alpha]
version = "0.15"

[dependencies.beta]
# oh yea
version = "15"

# oh yea
[dependencies.syn]
version = "0.1"

# oh yea
[workspace]
members = ["z", "b", "A", "f", "g"]
